package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComIswaryagrandhiMavenkotlin'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComIswaryagrandhiMavenkotlin")
    name = "https://github.com/iswaryagrandhi/mavenkotlin"
    url = "https://github.com/iswaryagrandhi/mavenkotlin"
    branch = "refs/heads/master"
    authMethod = password {
        userName = "iswaryagrandhi"
        password = "credentialsJSON:bf91cc2f-1e39-4e2b-a39f-fc43ea3382c4"
    }
}))

